In [1]:
import numpy as np

In [2]:
ages = np.array([22, 38, 26, 35, 28, 0, 54, 2, 27, 14])

In [3]:
ages.shape

(10,)

In [4]:
ages[0]

np.int64(22)

In [5]:
ages[2:5]

array([26, 35, 28])

In [6]:
ages.mean()

np.float64(24.6)

In [7]:
print(ages.mean())

24.6


In [8]:
print(ages[2])

26


In [9]:
print(ages[4:8])

[28  0 54  2]


In [10]:
ages_2d = np.array([[22, 38, 26, 35, 28],
                    [0, 54, 2, 27, 14]])

In [11]:
print(ages_2d)

[[22 38 26 35 28]
 [ 0 54  2 27 14]]


In [12]:
ages_2d.shape

(2, 5)

In [13]:
print(ages_2d[0])
print(ages_2d[1])  

[22 38 26 35 28]
[ 0 54  2 27 14]


In [14]:
print(ages_2d[0][1])
print(ages_2d[1][1])

38
54


In [17]:
ages_2d.mean()

np.float64(24.6)

In [23]:
print(ages_2d.max())
print(ages_2d.min())

54
0
